#!/usr/bin/env bash

# update package and install nginx services
sudo apt update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo tee /var/www/html/index.nginx-debian.html |echo "Hello World"
