#!/usr/bin/env bash

# update package and install nginx services
sudo apt update
sudo apt-get install nginx -y
sudo echo "Hello World" |sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
