#!/usr/bin/env bash
# update package and install nginx services
# Script that installs Nginx server and redirects /redirect_me

sudo apt update
sudo apt-get install nginx -y
sudo echo "Hello World" |sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=NdYWuo9OFAw permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
