#!/usr/bin/env bash
# update package and install nginx services
# Script that installs Nginx server and redirects /redirect_me

sudo apt update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www/
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/error-404.html
sudo service nginx start
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=NdYWuo9OFAw permanent;/" /etc/nginx/sites-available/default
# Configuring the Nginx server to have a custom 404
# page containing the string Ceci n'est pas une page.
sudo sed -i "s/^server\s{/server {\n\terror_page 404 \/error-404.html;/1" /etc/nginx/sites-available/default
sudo service nginx restart
